name: Build full image

on:
  workflow_dispatch:

concurrency:
  group: build-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  image-minimal:
    name: Build image-minimal
    runs-on: ubuntu-latest
    timeout-minutes: 360

    steps:
      - name: Reclaim space
        uses: insightsengineering/disk-space-reclaimer@v1
        with:
            android: true
            dotnet: true
            haskell: true
            large-packages: true
            swap-storage: true
            docker-images: true
      - name: Check out
        uses: actions/checkout@v4

      - name: Install Nix
        uses: cachix/install-nix-action@v31
        with:
          extra_nix_config: |
            experimental-features = nix-command flakes
            accept-flake-config = true

      - name: Build minimal image
        run: nix build .#image-minimal

      - name: Upload image
        uses: actions/upload-artifact@v4
        with:
          name: puredarwin-minimal
          path: result/puredarwin-minimal.img
          if-no-files-found: error
